// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: awm/v1/agent.proto

package awmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent registration details (used in Orchestrator.Connect)
type AgentRegistration struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentId            string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Tenant             string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	AgentType          string                 `protobuf:"bytes,3,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Capabilities       []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Labels             map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MaxConcurrentTasks int32                  `protobuf:"varint,6,opt,name=max_concurrent_tasks,json=maxConcurrentTasks,proto3" json:"max_concurrent_tasks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentRegistration) Reset() {
	*x = AgentRegistration{}
	mi := &file_awm_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegistration) ProtoMessage() {}

func (x *AgentRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegistration.ProtoReflect.Descriptor instead.
func (*AgentRegistration) Descriptor() ([]byte, []int) {
	return file_awm_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRegistration) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentRegistration) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *AgentRegistration) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *AgentRegistration) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentRegistration) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AgentRegistration) GetMaxConcurrentTasks() int32 {
	if x != nil {
		return x.MaxConcurrentTasks
	}
	return 0
}

// Task definition (used in assignments)
type Task struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkflowInstanceId string                 `protobuf:"bytes,2,opt,name=workflow_instance_id,json=workflowInstanceId,proto3" json:"workflow_instance_id,omitempty"`
	ActivityName       string                 `protobuf:"bytes,3,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`
	Input              *structpb.Struct       `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_awm_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_awm_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetWorkflowInstanceId() string {
	if x != nil {
		return x.WorkflowInstanceId
	}
	return ""
}

func (x *Task) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *Task) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Task) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Task outcome
type TaskOutcome struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*TaskOutcome_Success
	//	*TaskOutcome_Error
	Result        isTaskOutcome_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutcome) Reset() {
	*x = TaskOutcome{}
	mi := &file_awm_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutcome) ProtoMessage() {}

func (x *TaskOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutcome.ProtoReflect.Descriptor instead.
func (*TaskOutcome) Descriptor() ([]byte, []int) {
	return file_awm_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *TaskOutcome) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskOutcome) GetResult() isTaskOutcome_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskOutcome) GetSuccess() *structpb.Struct {
	if x != nil {
		if x, ok := x.Result.(*TaskOutcome_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *TaskOutcome) GetError() *TaskError {
	if x != nil {
		if x, ok := x.Result.(*TaskOutcome_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTaskOutcome_Result interface {
	isTaskOutcome_Result()
}

type TaskOutcome_Success struct {
	Success *structpb.Struct `protobuf:"bytes,2,opt,name=success,proto3,oneof"`
}

type TaskOutcome_Error struct {
	Error *TaskError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*TaskOutcome_Success) isTaskOutcome_Result() {}

func (*TaskOutcome_Error) isTaskOutcome_Result() {}

type TaskError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskError) Reset() {
	*x = TaskError{}
	mi := &file_awm_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskError) ProtoMessage() {}

func (x *TaskError) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskError.ProtoReflect.Descriptor instead.
func (*TaskError) Descriptor() ([]byte, []int) {
	return file_awm_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *TaskError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TaskError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskError) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *TaskError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_awm_v1_agent_proto protoreflect.FileDescriptor

const file_awm_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x12awm/v1/agent.proto\x12\x06awm.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xb5\x02\n" +
	"\x11AgentRegistration\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x03 \x01(\tR\tagentType\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12=\n" +
	"\x06labels\x18\x05 \x03(\v2%.awm.v1.AgentRegistration.LabelsEntryR\x06labels\x120\n" +
	"\x14max_concurrent_tasks\x18\x06 \x01(\x05R\x12maxConcurrentTasks\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x02\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x120\n" +
	"\x14workflow_instance_id\x18\x02 \x01(\tR\x12workflowInstanceId\x12#\n" +
	"\ractivity_name\x18\x03 \x01(\tR\factivityName\x12-\n" +
	"\x05input\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x05input\x126\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1a.awm.v1.Task.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\vTaskOutcome\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x123\n" +
	"\asuccess\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x00R\asuccess\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x11.awm.v1.TaskErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x8a\x01\n" +
	"\tTaskError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\adetails\x18\x03 \x01(\v2\x17.google.protobuf.StructR\adetails\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryableB5Z3github.com/autocondat/awm-proto/gen/go/awm/v1;awmv1b\x06proto3"

var (
	file_awm_v1_agent_proto_rawDescOnce sync.Once
	file_awm_v1_agent_proto_rawDescData []byte
)

func file_awm_v1_agent_proto_rawDescGZIP() []byte {
	file_awm_v1_agent_proto_rawDescOnce.Do(func() {
		file_awm_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_awm_v1_agent_proto_rawDesc), len(file_awm_v1_agent_proto_rawDesc)))
	})
	return file_awm_v1_agent_proto_rawDescData
}

var file_awm_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_awm_v1_agent_proto_goTypes = []any{
	(*AgentRegistration)(nil), // 0: awm.v1.AgentRegistration
	(*Task)(nil),              // 1: awm.v1.Task
	(*TaskOutcome)(nil),       // 2: awm.v1.TaskOutcome
	(*TaskError)(nil),         // 3: awm.v1.TaskError
	nil,                       // 4: awm.v1.AgentRegistration.LabelsEntry
	nil,                       // 5: awm.v1.Task.MetadataEntry
	(*structpb.Struct)(nil),   // 6: google.protobuf.Struct
}
var file_awm_v1_agent_proto_depIdxs = []int32{
	4, // 0: awm.v1.AgentRegistration.labels:type_name -> awm.v1.AgentRegistration.LabelsEntry
	6, // 1: awm.v1.Task.input:type_name -> google.protobuf.Struct
	5, // 2: awm.v1.Task.metadata:type_name -> awm.v1.Task.MetadataEntry
	6, // 3: awm.v1.TaskOutcome.success:type_name -> google.protobuf.Struct
	3, // 4: awm.v1.TaskOutcome.error:type_name -> awm.v1.TaskError
	6, // 5: awm.v1.TaskError.details:type_name -> google.protobuf.Struct
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_awm_v1_agent_proto_init() }
func file_awm_v1_agent_proto_init() {
	if File_awm_v1_agent_proto != nil {
		return
	}
	file_awm_v1_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*TaskOutcome_Success)(nil),
		(*TaskOutcome_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_awm_v1_agent_proto_rawDesc), len(file_awm_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_awm_v1_agent_proto_goTypes,
		DependencyIndexes: file_awm_v1_agent_proto_depIdxs,
		MessageInfos:      file_awm_v1_agent_proto_msgTypes,
	}.Build()
	File_awm_v1_agent_proto = out.File
	file_awm_v1_agent_proto_goTypes = nil
	file_awm_v1_agent_proto_depIdxs = nil
}
