// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: awm/v1/orchestrator.proto

package awmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowStatus int32

const (
	WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED WorkflowStatus = 0
	WorkflowStatus_WORKFLOW_STATUS_RUNNING     WorkflowStatus = 1
	WorkflowStatus_WORKFLOW_STATUS_SUSPENDED   WorkflowStatus = 2
	WorkflowStatus_WORKFLOW_STATUS_COMPLETED   WorkflowStatus = 3
	WorkflowStatus_WORKFLOW_STATUS_FAILED      WorkflowStatus = 4
	WorkflowStatus_WORKFLOW_STATUS_CANCELED    WorkflowStatus = 5
	WorkflowStatus_WORKFLOW_STATUS_WAITING     WorkflowStatus = 6
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNSPECIFIED",
		1: "WORKFLOW_STATUS_RUNNING",
		2: "WORKFLOW_STATUS_SUSPENDED",
		3: "WORKFLOW_STATUS_COMPLETED",
		4: "WORKFLOW_STATUS_FAILED",
		5: "WORKFLOW_STATUS_CANCELED",
		6: "WORKFLOW_STATUS_WAITING",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNSPECIFIED": 0,
		"WORKFLOW_STATUS_RUNNING":     1,
		"WORKFLOW_STATUS_SUSPENDED":   2,
		"WORKFLOW_STATUS_COMPLETED":   3,
		"WORKFLOW_STATUS_FAILED":      4,
		"WORKFLOW_STATUS_CANCELED":    5,
		"WORKFLOW_STATUS_WAITING":     6,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_awm_v1_orchestrator_proto_enumTypes[0].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_awm_v1_orchestrator_proto_enumTypes[0]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{0}
}

type AgentToServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*AgentToServer_Register
	//	*AgentToServer_TaskResult
	//	*AgentToServer_Heartbeat
	//	*AgentToServer_Disconnect
	Message       isAgentToServer_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToServer) Reset() {
	*x = AgentToServer{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToServer) ProtoMessage() {}

func (x *AgentToServer) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToServer.ProtoReflect.Descriptor instead.
func (*AgentToServer) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *AgentToServer) GetMessage() isAgentToServer_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AgentToServer) GetRegister() *RegisterAgent {
	if x != nil {
		if x, ok := x.Message.(*AgentToServer_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentToServer) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Message.(*AgentToServer_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *AgentToServer) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*AgentToServer_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentToServer) GetDisconnect() *AgentDisconnect {
	if x != nil {
		if x, ok := x.Message.(*AgentToServer_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

type isAgentToServer_Message interface {
	isAgentToServer_Message()
}

type AgentToServer_Register struct {
	Register *RegisterAgent `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentToServer_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,2,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type AgentToServer_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type AgentToServer_Disconnect struct {
	Disconnect *AgentDisconnect `protobuf:"bytes,4,opt,name=disconnect,proto3,oneof"`
}

func (*AgentToServer_Register) isAgentToServer_Message() {}

func (*AgentToServer_TaskResult) isAgentToServer_Message() {}

func (*AgentToServer_Heartbeat) isAgentToServer_Message() {}

func (*AgentToServer_Disconnect) isAgentToServer_Message() {}

type ServerToAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerToAgent_TaskAssignment
	//	*ServerToAgent_Signal
	//	*ServerToAgent_Ack
	Message       isServerToAgent_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToAgent) Reset() {
	*x = ServerToAgent{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToAgent) ProtoMessage() {}

func (x *ServerToAgent) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToAgent.ProtoReflect.Descriptor instead.
func (*ServerToAgent) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *ServerToAgent) GetMessage() isServerToAgent_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerToAgent) GetTaskAssignment() *TaskAssignment {
	if x != nil {
		if x, ok := x.Message.(*ServerToAgent_TaskAssignment); ok {
			return x.TaskAssignment
		}
	}
	return nil
}

func (x *ServerToAgent) GetSignal() *SignalWorkflow {
	if x != nil {
		if x, ok := x.Message.(*ServerToAgent_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *ServerToAgent) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Message.(*ServerToAgent_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isServerToAgent_Message interface {
	isServerToAgent_Message()
}

type ServerToAgent_TaskAssignment struct {
	TaskAssignment *TaskAssignment `protobuf:"bytes,1,opt,name=task_assignment,json=taskAssignment,proto3,oneof"`
}

type ServerToAgent_Signal struct {
	Signal *SignalWorkflow `protobuf:"bytes,2,opt,name=signal,proto3,oneof"`
}

type ServerToAgent_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*ServerToAgent_TaskAssignment) isServerToAgent_Message() {}

func (*ServerToAgent_Signal) isServerToAgent_Message() {}

func (*ServerToAgent_Ack) isServerToAgent_Message() {}

type RegisterAgent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentId            string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Tenant             string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	AgentType          string                 `protobuf:"bytes,3,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"` // "human_cli", "ai_runner", "service"
	Capabilities       []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`            // e.g., ["estimate_story", "write_code"]
	Labels             map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MaxConcurrentTasks int32                  `protobuf:"varint,6,opt,name=max_concurrent_tasks,json=maxConcurrentTasks,proto3" json:"max_concurrent_tasks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterAgent) Reset() {
	*x = RegisterAgent{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgent) ProtoMessage() {}

func (x *RegisterAgent) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgent.ProtoReflect.Descriptor instead.
func (*RegisterAgent) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAgent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgent) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *RegisterAgent) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *RegisterAgent) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterAgent) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterAgent) GetMaxConcurrentTasks() int32 {
	if x != nil {
		return x.MaxConcurrentTasks
	}
	return 0
}

type TaskAssignment struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkflowInstanceId string                 `protobuf:"bytes,2,opt,name=workflow_instance_id,json=workflowInstanceId,proto3" json:"workflow_instance_id,omitempty"`
	ActivityName       string                 `protobuf:"bytes,3,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`
	Input              *structpb.Struct       `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Deadline           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetWorkflowInstanceId() string {
	if x != nil {
		return x.WorkflowInstanceId
	}
	return ""
}

func (x *TaskAssignment) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *TaskAssignment) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TaskAssignment) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *TaskAssignment) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TaskResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*TaskResult_Success
	//	*TaskResult_Error
	Outcome       isTaskResult_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetOutcome() isTaskResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *TaskResult) GetSuccess() *structpb.Struct {
	if x != nil {
		if x, ok := x.Outcome.(*TaskResult_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *TaskResult) GetError() *TaskError {
	if x != nil {
		if x, ok := x.Outcome.(*TaskResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTaskResult_Outcome interface {
	isTaskResult_Outcome()
}

type TaskResult_Success struct {
	Success *structpb.Struct `protobuf:"bytes,2,opt,name=success,proto3,oneof"`
}

type TaskResult_Error struct {
	Error *TaskError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*TaskResult_Success) isTaskResult_Outcome() {}

func (*TaskResult_Error) isTaskResult_Outcome() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ActiveTaskIds []string               `protobuf:"bytes,2,rep,name=active_task_ids,json=activeTaskIds,proto3" json:"active_task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetActiveTaskIds() []string {
	if x != nil {
		return x.ActiveTaskIds
	}
	return nil
}

type AgentDisconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDisconnect) Reset() {
	*x = AgentDisconnect{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDisconnect) ProtoMessage() {}

func (x *AgentDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDisconnect.ProtoReflect.Descriptor instead.
func (*AgentDisconnect) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *AgentDisconnect) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *Ack) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SignalWorkflow struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkflowInstanceId string                 `protobuf:"bytes,1,opt,name=workflow_instance_id,json=workflowInstanceId,proto3" json:"workflow_instance_id,omitempty"`
	SignalName         string                 `protobuf:"bytes,2,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	Payload            *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignalWorkflow) Reset() {
	*x = SignalWorkflow{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalWorkflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalWorkflow) ProtoMessage() {}

func (x *SignalWorkflow) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalWorkflow.ProtoReflect.Descriptor instead.
func (*SignalWorkflow) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *SignalWorkflow) GetWorkflowInstanceId() string {
	if x != nil {
		return x.WorkflowInstanceId
	}
	return ""
}

func (x *SignalWorkflow) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *SignalWorkflow) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PollTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTaskRequest) Reset() {
	*x = PollTaskRequest{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTaskRequest) ProtoMessage() {}

func (x *PollTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTaskRequest.ProtoReflect.Descriptor instead.
func (*PollTaskRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *PollTaskRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PollTaskRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type PollTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskAssignment        `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTaskResponse) Reset() {
	*x = PollTaskResponse{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTaskResponse) ProtoMessage() {}

func (x *PollTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTaskResponse.ProtoReflect.Descriptor instead.
func (*PollTaskResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *PollTaskResponse) GetTask() *TaskAssignment {
	if x != nil {
		return x.Task
	}
	return nil
}

type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result        *structpb.Struct       `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *CompleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CompleteTaskRequest) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

type CompleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskResponse) Reset() {
	*x = CompleteTaskResponse{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskResponse) ProtoMessage() {}

func (x *CompleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskResponse.ProtoReflect.Descriptor instead.
func (*CompleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteTaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type FailTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Error         *TaskError             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailTaskRequest) Reset() {
	*x = FailTaskRequest{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailTaskRequest) ProtoMessage() {}

func (x *FailTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailTaskRequest.ProtoReflect.Descriptor instead.
func (*FailTaskRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *FailTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FailTaskRequest) GetError() *TaskError {
	if x != nil {
		return x.Error
	}
	return nil
}

type FailTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailTaskResponse) Reset() {
	*x = FailTaskResponse{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailTaskResponse) ProtoMessage() {}

func (x *FailTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailTaskResponse.ProtoReflect.Descriptor instead.
func (*FailTaskResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *FailTaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ExtendTaskLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NewDeadline   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=new_deadline,json=newDeadline,proto3" json:"new_deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendTaskLeaseRequest) Reset() {
	*x = ExtendTaskLeaseRequest{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendTaskLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendTaskLeaseRequest) ProtoMessage() {}

func (x *ExtendTaskLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendTaskLeaseRequest.ProtoReflect.Descriptor instead.
func (*ExtendTaskLeaseRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *ExtendTaskLeaseRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExtendTaskLeaseRequest) GetNewDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.NewDeadline
	}
	return nil
}

type ExtendTaskLeaseResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Granted        bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	ActualDeadline *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=actual_deadline,json=actualDeadline,proto3" json:"actual_deadline,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExtendTaskLeaseResponse) Reset() {
	*x = ExtendTaskLeaseResponse{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendTaskLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendTaskLeaseResponse) ProtoMessage() {}

func (x *ExtendTaskLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendTaskLeaseResponse.ProtoReflect.Descriptor instead.
func (*ExtendTaskLeaseResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *ExtendTaskLeaseResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *ExtendTaskLeaseResponse) GetActualDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.ActualDeadline
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ActiveTaskIds []string               `protobuf:"bytes,2,rep,name=active_task_ids,json=activeTaskIds,proto3" json:"active_task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetActiveTaskIds() []string {
	if x != nil {
		return x.ActiveTaskIds
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{18}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetWorkflowStateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkflowInstanceId string                 `protobuf:"bytes,1,opt,name=workflow_instance_id,json=workflowInstanceId,proto3" json:"workflow_instance_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetWorkflowStateRequest) Reset() {
	*x = GetWorkflowStateRequest{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStateRequest) ProtoMessage() {}

func (x *GetWorkflowStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStateRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowStateRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{19}
}

func (x *GetWorkflowStateRequest) GetWorkflowInstanceId() string {
	if x != nil {
		return x.WorkflowInstanceId
	}
	return ""
}

type GetWorkflowStateResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorkflowInstanceId   string                 `protobuf:"bytes,1,opt,name=workflow_instance_id,json=workflowInstanceId,proto3" json:"workflow_instance_id,omitempty"`
	WorkflowDefinitionId string                 `protobuf:"bytes,2,opt,name=workflow_definition_id,json=workflowDefinitionId,proto3" json:"workflow_definition_id,omitempty"`
	Status               WorkflowStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=awm.v1.WorkflowStatus" json:"status,omitempty"`
	DimensionalState     *structpb.Struct       `protobuf:"bytes,4,opt,name=dimensional_state,json=dimensionalState,proto3" json:"dimensional_state,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	NextTimeout          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=next_timeout,json=nextTimeout,proto3" json:"next_timeout,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetWorkflowStateResponse) Reset() {
	*x = GetWorkflowStateResponse{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStateResponse) ProtoMessage() {}

func (x *GetWorkflowStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStateResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowStateResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{20}
}

func (x *GetWorkflowStateResponse) GetWorkflowInstanceId() string {
	if x != nil {
		return x.WorkflowInstanceId
	}
	return ""
}

func (x *GetWorkflowStateResponse) GetWorkflowDefinitionId() string {
	if x != nil {
		return x.WorkflowDefinitionId
	}
	return ""
}

func (x *GetWorkflowStateResponse) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *GetWorkflowStateResponse) GetDimensionalState() *structpb.Struct {
	if x != nil {
		return x.DimensionalState
	}
	return nil
}

func (x *GetWorkflowStateResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetWorkflowStateResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetWorkflowStateResponse) GetNextTimeout() *timestamppb.Timestamp {
	if x != nil {
		return x.NextTimeout
	}
	return nil
}

type ListWorkflowsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Tenant               string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	WorkflowDefinitionId string                 `protobuf:"bytes,2,opt,name=workflow_definition_id,json=workflowDefinitionId,proto3" json:"workflow_definition_id,omitempty"`
	StatusFilter         WorkflowStatus         `protobuf:"varint,3,opt,name=status_filter,json=statusFilter,proto3,enum=awm.v1.WorkflowStatus" json:"status_filter,omitempty"`
	PageSize             int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{21}
}

func (x *ListWorkflowsRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ListWorkflowsRequest) GetWorkflowDefinitionId() string {
	if x != nil {
		return x.WorkflowDefinitionId
	}
	return ""
}

func (x *ListWorkflowsRequest) GetStatusFilter() WorkflowStatus {
	if x != nil {
		return x.StatusFilter
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *ListWorkflowsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorkflowsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*WorkflowSummary     `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{22}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*WorkflowSummary {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *ListWorkflowsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type WorkflowSummary struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorkflowInstanceId   string                 `protobuf:"bytes,1,opt,name=workflow_instance_id,json=workflowInstanceId,proto3" json:"workflow_instance_id,omitempty"`
	WorkflowDefinitionId string                 `protobuf:"bytes,2,opt,name=workflow_definition_id,json=workflowDefinitionId,proto3" json:"workflow_definition_id,omitempty"`
	Status               WorkflowStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=awm.v1.WorkflowStatus" json:"status,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WorkflowSummary) Reset() {
	*x = WorkflowSummary{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowSummary) ProtoMessage() {}

func (x *WorkflowSummary) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowSummary.ProtoReflect.Descriptor instead.
func (*WorkflowSummary) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{23}
}

func (x *WorkflowSummary) GetWorkflowInstanceId() string {
	if x != nil {
		return x.WorkflowInstanceId
	}
	return ""
}

func (x *WorkflowSummary) GetWorkflowDefinitionId() string {
	if x != nil {
		return x.WorkflowDefinitionId
	}
	return ""
}

func (x *WorkflowSummary) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type StreamWorkflowEventsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkflowInstanceId string                 `protobuf:"bytes,1,opt,name=workflow_instance_id,json=workflowInstanceId,proto3" json:"workflow_instance_id,omitempty"`
	AfterSequence      int64                  `protobuf:"varint,2,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamWorkflowEventsRequest) Reset() {
	*x = StreamWorkflowEventsRequest{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamWorkflowEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWorkflowEventsRequest) ProtoMessage() {}

func (x *StreamWorkflowEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWorkflowEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamWorkflowEventsRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{24}
}

func (x *StreamWorkflowEventsRequest) GetWorkflowInstanceId() string {
	if x != nil {
		return x.WorkflowInstanceId
	}
	return ""
}

func (x *StreamWorkflowEventsRequest) GetAfterSequence() int64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

type WorkflowEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceNum   int64                  `protobuf:"varint,1,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowEvent) Reset() {
	*x = WorkflowEvent{}
	mi := &file_awm_v1_orchestrator_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowEvent) ProtoMessage() {}

func (x *WorkflowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_orchestrator_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowEvent.ProtoReflect.Descriptor instead.
func (*WorkflowEvent) Descriptor() ([]byte, []int) {
	return file_awm_v1_orchestrator_proto_rawDescGZIP(), []int{25}
}

func (x *WorkflowEvent) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *WorkflowEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WorkflowEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WorkflowEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_awm_v1_orchestrator_proto protoreflect.FileDescriptor

const file_awm_v1_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x19awm/v1/orchestrator.proto\x12\x06awm.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12awm/v1/agent.proto\"\xf4\x01\n" +
	"\rAgentToServer\x123\n" +
	"\bregister\x18\x01 \x01(\v2\x15.awm.v1.RegisterAgentH\x00R\bregister\x125\n" +
	"\vtask_result\x18\x02 \x01(\v2\x12.awm.v1.TaskResultH\x00R\n" +
	"taskResult\x121\n" +
	"\theartbeat\x18\x03 \x01(\v2\x11.awm.v1.HeartbeatH\x00R\theartbeat\x129\n" +
	"\n" +
	"disconnect\x18\x04 \x01(\v2\x17.awm.v1.AgentDisconnectH\x00R\n" +
	"disconnectB\t\n" +
	"\amessage\"\xb0\x01\n" +
	"\rServerToAgent\x12A\n" +
	"\x0ftask_assignment\x18\x01 \x01(\v2\x16.awm.v1.TaskAssignmentH\x00R\x0etaskAssignment\x120\n" +
	"\x06signal\x18\x02 \x01(\v2\x16.awm.v1.SignalWorkflowH\x00R\x06signal\x12\x1f\n" +
	"\x03ack\x18\x03 \x01(\v2\v.awm.v1.AckH\x00R\x03ackB\t\n" +
	"\amessage\"\xad\x02\n" +
	"\rRegisterAgent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x03 \x01(\tR\tagentType\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x129\n" +
	"\x06labels\x18\x05 \x03(\v2!.awm.v1.RegisterAgent.LabelsEntryR\x06labels\x120\n" +
	"\x14max_concurrent_tasks\x18\x06 \x01(\x05R\x12maxConcurrentTasks\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x02\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x120\n" +
	"\x14workflow_instance_id\x18\x02 \x01(\tR\x12workflowInstanceId\x12#\n" +
	"\ractivity_name\x18\x03 \x01(\tR\factivityName\x12-\n" +
	"\x05input\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x05input\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12@\n" +
	"\bmetadata\x18\x06 \x03(\v2$.awm.v1.TaskAssignment.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x123\n" +
	"\asuccess\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x00R\asuccess\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x11.awm.v1.TaskErrorH\x00R\x05errorB\t\n" +
	"\aoutcome\"N\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12&\n" +
	"\x0factive_task_ids\x18\x02 \x03(\tR\ractiveTaskIds\")\n" +
	"\x0fAgentDisconnect\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\">\n" +
	"\x03Ack\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x96\x01\n" +
	"\x0eSignalWorkflow\x120\n" +
	"\x14workflow_instance_id\x18\x01 \x01(\tR\x12workflowInstanceId\x12\x1f\n" +
	"\vsignal_name\x18\x02 \x01(\tR\n" +
	"signalName\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\"D\n" +
	"\x0fPollTaskRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\">\n" +
	"\x10PollTaskResponse\x12*\n" +
	"\x04task\x18\x01 \x01(\v2\x16.awm.v1.TaskAssignmentR\x04task\"_\n" +
	"\x13CompleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06result\"2\n" +
	"\x14CompleteTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"S\n" +
	"\x0fFailTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x11.awm.v1.TaskErrorR\x05error\".\n" +
	"\x10FailTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"p\n" +
	"\x16ExtendTaskLeaseRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12=\n" +
	"\fnew_deadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vnewDeadline\"x\n" +
	"\x17ExtendTaskLeaseResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12C\n" +
	"\x0factual_deadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0eactualDeadline\"U\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12&\n" +
	"\x0factive_task_ids\x18\x02 \x03(\tR\ractiveTaskIds\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"K\n" +
	"\x17GetWorkflowStateRequest\x120\n" +
	"\x14workflow_instance_id\x18\x01 \x01(\tR\x12workflowInstanceId\"\xad\x03\n" +
	"\x18GetWorkflowStateResponse\x120\n" +
	"\x14workflow_instance_id\x18\x01 \x01(\tR\x12workflowInstanceId\x124\n" +
	"\x16workflow_definition_id\x18\x02 \x01(\tR\x14workflowDefinitionId\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.awm.v1.WorkflowStatusR\x06status\x12D\n" +
	"\x11dimensional_state\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x10dimensionalState\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fnext_timeout\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vnextTimeout\"\xdd\x01\n" +
	"\x14ListWorkflowsRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x124\n" +
	"\x16workflow_definition_id\x18\x02 \x01(\tR\x14workflowDefinitionId\x12;\n" +
	"\rstatus_filter\x18\x03 \x01(\x0e2\x16.awm.v1.WorkflowStatusR\fstatusFilter\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"v\n" +
	"\x15ListWorkflowsResponse\x125\n" +
	"\tworkflows\x18\x01 \x03(\v2\x17.awm.v1.WorkflowSummaryR\tworkflows\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xe4\x01\n" +
	"\x0fWorkflowSummary\x120\n" +
	"\x14workflow_instance_id\x18\x01 \x01(\tR\x12workflowInstanceId\x124\n" +
	"\x16workflow_definition_id\x18\x02 \x01(\tR\x14workflowDefinitionId\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.awm.v1.WorkflowStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"v\n" +
	"\x1bStreamWorkflowEventsRequest\x120\n" +
	"\x14workflow_instance_id\x18\x01 \x01(\tR\x12workflowInstanceId\x12%\n" +
	"\x0eafter_sequence\x18\x02 \x01(\x03R\rafterSequence\"\xbe\x01\n" +
	"\rWorkflowEvent\x12!\n" +
	"\fsequence_num\x18\x01 \x01(\x03R\vsequenceNum\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload*\xe3\x01\n" +
	"\x0eWorkflowStatus\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_RUNNING\x10\x01\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_SUSPENDED\x10\x02\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_COMPLETED\x10\x03\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_FAILED\x10\x04\x12\x1c\n" +
	"\x18WORKFLOW_STATUS_CANCELED\x10\x05\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_WAITING\x10\x062\xa5\x05\n" +
	"\fOrchestrator\x12;\n" +
	"\aConnect\x12\x15.awm.v1.AgentToServer\x1a\x15.awm.v1.ServerToAgent(\x010\x01\x12=\n" +
	"\bPollTask\x12\x17.awm.v1.PollTaskRequest\x1a\x18.awm.v1.PollTaskResponse\x12I\n" +
	"\fCompleteTask\x12\x1b.awm.v1.CompleteTaskRequest\x1a\x1c.awm.v1.CompleteTaskResponse\x12=\n" +
	"\bFailTask\x12\x17.awm.v1.FailTaskRequest\x1a\x18.awm.v1.FailTaskResponse\x12R\n" +
	"\x0fExtendTaskLease\x12\x1e.awm.v1.ExtendTaskLeaseRequest\x1a\x1f.awm.v1.ExtendTaskLeaseResponse\x12@\n" +
	"\tHeartbeat\x12\x18.awm.v1.HeartbeatRequest\x1a\x19.awm.v1.HeartbeatResponse\x12U\n" +
	"\x10GetWorkflowState\x12\x1f.awm.v1.GetWorkflowStateRequest\x1a .awm.v1.GetWorkflowStateResponse\x12L\n" +
	"\rListWorkflows\x12\x1c.awm.v1.ListWorkflowsRequest\x1a\x1d.awm.v1.ListWorkflowsResponse\x12T\n" +
	"\x14StreamWorkflowEvents\x12#.awm.v1.StreamWorkflowEventsRequest\x1a\x15.awm.v1.WorkflowEvent0\x01B5Z3github.com/autocondat/awm-proto/gen/go/awm/v1;awmv1b\x06proto3"

var (
	file_awm_v1_orchestrator_proto_rawDescOnce sync.Once
	file_awm_v1_orchestrator_proto_rawDescData []byte
)

func file_awm_v1_orchestrator_proto_rawDescGZIP() []byte {
	file_awm_v1_orchestrator_proto_rawDescOnce.Do(func() {
		file_awm_v1_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_awm_v1_orchestrator_proto_rawDesc), len(file_awm_v1_orchestrator_proto_rawDesc)))
	})
	return file_awm_v1_orchestrator_proto_rawDescData
}

var file_awm_v1_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_awm_v1_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_awm_v1_orchestrator_proto_goTypes = []any{
	(WorkflowStatus)(0),                 // 0: awm.v1.WorkflowStatus
	(*AgentToServer)(nil),               // 1: awm.v1.AgentToServer
	(*ServerToAgent)(nil),               // 2: awm.v1.ServerToAgent
	(*RegisterAgent)(nil),               // 3: awm.v1.RegisterAgent
	(*TaskAssignment)(nil),              // 4: awm.v1.TaskAssignment
	(*TaskResult)(nil),                  // 5: awm.v1.TaskResult
	(*Heartbeat)(nil),                   // 6: awm.v1.Heartbeat
	(*AgentDisconnect)(nil),             // 7: awm.v1.AgentDisconnect
	(*Ack)(nil),                         // 8: awm.v1.Ack
	(*SignalWorkflow)(nil),              // 9: awm.v1.SignalWorkflow
	(*PollTaskRequest)(nil),             // 10: awm.v1.PollTaskRequest
	(*PollTaskResponse)(nil),            // 11: awm.v1.PollTaskResponse
	(*CompleteTaskRequest)(nil),         // 12: awm.v1.CompleteTaskRequest
	(*CompleteTaskResponse)(nil),        // 13: awm.v1.CompleteTaskResponse
	(*FailTaskRequest)(nil),             // 14: awm.v1.FailTaskRequest
	(*FailTaskResponse)(nil),            // 15: awm.v1.FailTaskResponse
	(*ExtendTaskLeaseRequest)(nil),      // 16: awm.v1.ExtendTaskLeaseRequest
	(*ExtendTaskLeaseResponse)(nil),     // 17: awm.v1.ExtendTaskLeaseResponse
	(*HeartbeatRequest)(nil),            // 18: awm.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 19: awm.v1.HeartbeatResponse
	(*GetWorkflowStateRequest)(nil),     // 20: awm.v1.GetWorkflowStateRequest
	(*GetWorkflowStateResponse)(nil),    // 21: awm.v1.GetWorkflowStateResponse
	(*ListWorkflowsRequest)(nil),        // 22: awm.v1.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil),       // 23: awm.v1.ListWorkflowsResponse
	(*WorkflowSummary)(nil),             // 24: awm.v1.WorkflowSummary
	(*StreamWorkflowEventsRequest)(nil), // 25: awm.v1.StreamWorkflowEventsRequest
	(*WorkflowEvent)(nil),               // 26: awm.v1.WorkflowEvent
	nil,                                 // 27: awm.v1.RegisterAgent.LabelsEntry
	nil,                                 // 28: awm.v1.TaskAssignment.MetadataEntry
	(*structpb.Struct)(nil),             // 29: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),       // 30: google.protobuf.Timestamp
	(*TaskError)(nil),                   // 31: awm.v1.TaskError
}
var file_awm_v1_orchestrator_proto_depIdxs = []int32{
	3,  // 0: awm.v1.AgentToServer.register:type_name -> awm.v1.RegisterAgent
	5,  // 1: awm.v1.AgentToServer.task_result:type_name -> awm.v1.TaskResult
	6,  // 2: awm.v1.AgentToServer.heartbeat:type_name -> awm.v1.Heartbeat
	7,  // 3: awm.v1.AgentToServer.disconnect:type_name -> awm.v1.AgentDisconnect
	4,  // 4: awm.v1.ServerToAgent.task_assignment:type_name -> awm.v1.TaskAssignment
	9,  // 5: awm.v1.ServerToAgent.signal:type_name -> awm.v1.SignalWorkflow
	8,  // 6: awm.v1.ServerToAgent.ack:type_name -> awm.v1.Ack
	27, // 7: awm.v1.RegisterAgent.labels:type_name -> awm.v1.RegisterAgent.LabelsEntry
	29, // 8: awm.v1.TaskAssignment.input:type_name -> google.protobuf.Struct
	30, // 9: awm.v1.TaskAssignment.deadline:type_name -> google.protobuf.Timestamp
	28, // 10: awm.v1.TaskAssignment.metadata:type_name -> awm.v1.TaskAssignment.MetadataEntry
	29, // 11: awm.v1.TaskResult.success:type_name -> google.protobuf.Struct
	31, // 12: awm.v1.TaskResult.error:type_name -> awm.v1.TaskError
	29, // 13: awm.v1.SignalWorkflow.payload:type_name -> google.protobuf.Struct
	4,  // 14: awm.v1.PollTaskResponse.task:type_name -> awm.v1.TaskAssignment
	29, // 15: awm.v1.CompleteTaskRequest.result:type_name -> google.protobuf.Struct
	31, // 16: awm.v1.FailTaskRequest.error:type_name -> awm.v1.TaskError
	30, // 17: awm.v1.ExtendTaskLeaseRequest.new_deadline:type_name -> google.protobuf.Timestamp
	30, // 18: awm.v1.ExtendTaskLeaseResponse.actual_deadline:type_name -> google.protobuf.Timestamp
	0,  // 19: awm.v1.GetWorkflowStateResponse.status:type_name -> awm.v1.WorkflowStatus
	29, // 20: awm.v1.GetWorkflowStateResponse.dimensional_state:type_name -> google.protobuf.Struct
	30, // 21: awm.v1.GetWorkflowStateResponse.created_at:type_name -> google.protobuf.Timestamp
	30, // 22: awm.v1.GetWorkflowStateResponse.updated_at:type_name -> google.protobuf.Timestamp
	30, // 23: awm.v1.GetWorkflowStateResponse.next_timeout:type_name -> google.protobuf.Timestamp
	0,  // 24: awm.v1.ListWorkflowsRequest.status_filter:type_name -> awm.v1.WorkflowStatus
	24, // 25: awm.v1.ListWorkflowsResponse.workflows:type_name -> awm.v1.WorkflowSummary
	0,  // 26: awm.v1.WorkflowSummary.status:type_name -> awm.v1.WorkflowStatus
	30, // 27: awm.v1.WorkflowSummary.created_at:type_name -> google.protobuf.Timestamp
	30, // 28: awm.v1.WorkflowEvent.timestamp:type_name -> google.protobuf.Timestamp
	29, // 29: awm.v1.WorkflowEvent.payload:type_name -> google.protobuf.Struct
	1,  // 30: awm.v1.Orchestrator.Connect:input_type -> awm.v1.AgentToServer
	10, // 31: awm.v1.Orchestrator.PollTask:input_type -> awm.v1.PollTaskRequest
	12, // 32: awm.v1.Orchestrator.CompleteTask:input_type -> awm.v1.CompleteTaskRequest
	14, // 33: awm.v1.Orchestrator.FailTask:input_type -> awm.v1.FailTaskRequest
	16, // 34: awm.v1.Orchestrator.ExtendTaskLease:input_type -> awm.v1.ExtendTaskLeaseRequest
	18, // 35: awm.v1.Orchestrator.Heartbeat:input_type -> awm.v1.HeartbeatRequest
	20, // 36: awm.v1.Orchestrator.GetWorkflowState:input_type -> awm.v1.GetWorkflowStateRequest
	22, // 37: awm.v1.Orchestrator.ListWorkflows:input_type -> awm.v1.ListWorkflowsRequest
	25, // 38: awm.v1.Orchestrator.StreamWorkflowEvents:input_type -> awm.v1.StreamWorkflowEventsRequest
	2,  // 39: awm.v1.Orchestrator.Connect:output_type -> awm.v1.ServerToAgent
	11, // 40: awm.v1.Orchestrator.PollTask:output_type -> awm.v1.PollTaskResponse
	13, // 41: awm.v1.Orchestrator.CompleteTask:output_type -> awm.v1.CompleteTaskResponse
	15, // 42: awm.v1.Orchestrator.FailTask:output_type -> awm.v1.FailTaskResponse
	17, // 43: awm.v1.Orchestrator.ExtendTaskLease:output_type -> awm.v1.ExtendTaskLeaseResponse
	19, // 44: awm.v1.Orchestrator.Heartbeat:output_type -> awm.v1.HeartbeatResponse
	21, // 45: awm.v1.Orchestrator.GetWorkflowState:output_type -> awm.v1.GetWorkflowStateResponse
	23, // 46: awm.v1.Orchestrator.ListWorkflows:output_type -> awm.v1.ListWorkflowsResponse
	26, // 47: awm.v1.Orchestrator.StreamWorkflowEvents:output_type -> awm.v1.WorkflowEvent
	39, // [39:48] is the sub-list for method output_type
	30, // [30:39] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_awm_v1_orchestrator_proto_init() }
func file_awm_v1_orchestrator_proto_init() {
	if File_awm_v1_orchestrator_proto != nil {
		return
	}
	file_awm_v1_agent_proto_init()
	file_awm_v1_orchestrator_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentToServer_Register)(nil),
		(*AgentToServer_TaskResult)(nil),
		(*AgentToServer_Heartbeat)(nil),
		(*AgentToServer_Disconnect)(nil),
	}
	file_awm_v1_orchestrator_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerToAgent_TaskAssignment)(nil),
		(*ServerToAgent_Signal)(nil),
		(*ServerToAgent_Ack)(nil),
	}
	file_awm_v1_orchestrator_proto_msgTypes[4].OneofWrappers = []any{
		(*TaskResult_Success)(nil),
		(*TaskResult_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_awm_v1_orchestrator_proto_rawDesc), len(file_awm_v1_orchestrator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_awm_v1_orchestrator_proto_goTypes,
		DependencyIndexes: file_awm_v1_orchestrator_proto_depIdxs,
		EnumInfos:         file_awm_v1_orchestrator_proto_enumTypes,
		MessageInfos:      file_awm_v1_orchestrator_proto_msgTypes,
	}.Build()
	File_awm_v1_orchestrator_proto = out.File
	file_awm_v1_orchestrator_proto_goTypes = nil
	file_awm_v1_orchestrator_proto_depIdxs = nil
}
