// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: awm/v1/public.proto

package awmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstanceStatus int32

const (
	InstanceStatus_INSTANCE_STATUS_UNSPECIFIED  InstanceStatus = 0
	InstanceStatus_INSTANCE_STATUS_PROVISIONING InstanceStatus = 1
	InstanceStatus_INSTANCE_STATUS_ACTIVE       InstanceStatus = 2
	InstanceStatus_INSTANCE_STATUS_DEGRADED     InstanceStatus = 3
	InstanceStatus_INSTANCE_STATUS_STOPPED      InstanceStatus = 4
	InstanceStatus_INSTANCE_STATUS_ARCHIVED     InstanceStatus = 5
)

// Enum value maps for InstanceStatus.
var (
	InstanceStatus_name = map[int32]string{
		0: "INSTANCE_STATUS_UNSPECIFIED",
		1: "INSTANCE_STATUS_PROVISIONING",
		2: "INSTANCE_STATUS_ACTIVE",
		3: "INSTANCE_STATUS_DEGRADED",
		4: "INSTANCE_STATUS_STOPPED",
		5: "INSTANCE_STATUS_ARCHIVED",
	}
	InstanceStatus_value = map[string]int32{
		"INSTANCE_STATUS_UNSPECIFIED":  0,
		"INSTANCE_STATUS_PROVISIONING": 1,
		"INSTANCE_STATUS_ACTIVE":       2,
		"INSTANCE_STATUS_DEGRADED":     3,
		"INSTANCE_STATUS_STOPPED":      4,
		"INSTANCE_STATUS_ARCHIVED":     5,
	}
)

func (x InstanceStatus) Enum() *InstanceStatus {
	p := new(InstanceStatus)
	*p = x
	return p
}

func (x InstanceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_awm_v1_public_proto_enumTypes[0].Descriptor()
}

func (InstanceStatus) Type() protoreflect.EnumType {
	return &file_awm_v1_public_proto_enumTypes[0]
}

func (x InstanceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstanceStatus.Descriptor instead.
func (InstanceStatus) EnumDescriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{0}
}

type WorkflowDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // internal UUID
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                     // human label
	DefinitionId  string                 `protobuf:"bytes,4,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"` // "id" field from the YAML
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	YamlContent   string                 `protobuf:"bytes,6,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"` // raw YAML as uploaded
	CreatedBy     string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowDefinition) Reset() {
	*x = WorkflowDefinition{}
	mi := &file_awm_v1_public_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDefinition) ProtoMessage() {}

func (x *WorkflowDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDefinition.ProtoReflect.Descriptor instead.
func (*WorkflowDefinition) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowDefinition) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *WorkflowDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowDefinition) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

func (x *WorkflowDefinition) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WorkflowDefinition) GetYamlContent() string {
	if x != nil {
		return x.YamlContent
	}
	return ""
}

func (x *WorkflowDefinition) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *WorkflowDefinition) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkflowDefinition) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateWorkflowDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                  // human label for this definition
	YamlContent   string                 `protobuf:"bytes,3,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"` // full YAML file contents
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`       // agent_id or user identifier of the uploader
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowDefinitionRequest) Reset() {
	*x = CreateWorkflowDefinitionRequest{}
	mi := &file_awm_v1_public_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowDefinitionRequest) ProtoMessage() {}

func (x *CreateWorkflowDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowDefinitionRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkflowDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorkflowDefinitionRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *CreateWorkflowDefinitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkflowDefinitionRequest) GetYamlContent() string {
	if x != nil {
		return x.YamlContent
	}
	return ""
}

func (x *CreateWorkflowDefinitionRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type GetWorkflowDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // internal UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowDefinitionRequest) Reset() {
	*x = GetWorkflowDefinitionRequest{}
	mi := &file_awm_v1_public_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowDefinitionRequest) ProtoMessage() {}

func (x *GetWorkflowDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowDefinitionRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkflowDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateWorkflowDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	YamlContent   string                 `protobuf:"bytes,2,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"` // replaces current content; bumps version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkflowDefinitionRequest) Reset() {
	*x = UpdateWorkflowDefinitionRequest{}
	mi := &file_awm_v1_public_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkflowDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkflowDefinitionRequest) ProtoMessage() {}

func (x *UpdateWorkflowDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkflowDefinitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkflowDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWorkflowDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWorkflowDefinitionRequest) GetYamlContent() string {
	if x != nil {
		return x.YamlContent
	}
	return ""
}

type DeleteWorkflowDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkflowDefinitionRequest) Reset() {
	*x = DeleteWorkflowDefinitionRequest{}
	mi := &file_awm_v1_public_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkflowDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkflowDefinitionRequest) ProtoMessage() {}

func (x *DeleteWorkflowDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkflowDefinitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkflowDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteWorkflowDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWorkflowDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkflowDefinitionResponse) Reset() {
	*x = DeleteWorkflowDefinitionResponse{}
	mi := &file_awm_v1_public_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkflowDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkflowDefinitionResponse) ProtoMessage() {}

func (x *DeleteWorkflowDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkflowDefinitionResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkflowDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteWorkflowDefinitionResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ListWorkflowDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	NameFilter    string                 `protobuf:"bytes,2,opt,name=name_filter,json=nameFilter,proto3" json:"name_filter,omitempty"` // optional substring match on name
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowDefinitionsRequest) Reset() {
	*x = ListWorkflowDefinitionsRequest{}
	mi := &file_awm_v1_public_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowDefinitionsRequest) ProtoMessage() {}

func (x *ListWorkflowDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkflowDefinitionsRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ListWorkflowDefinitionsRequest) GetNameFilter() string {
	if x != nil {
		return x.NameFilter
	}
	return ""
}

func (x *ListWorkflowDefinitionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorkflowDefinitionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListWorkflowDefinitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definitions   []*WorkflowDefinition  `protobuf:"bytes,1,rep,name=definitions,proto3" json:"definitions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowDefinitionsResponse) Reset() {
	*x = ListWorkflowDefinitionsResponse{}
	mi := &file_awm_v1_public_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowDefinitionsResponse) ProtoMessage() {}

func (x *ListWorkflowDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{7}
}

func (x *ListWorkflowDefinitionsResponse) GetDefinitions() []*WorkflowDefinition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *ListWorkflowDefinitionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type OrchestratorInstance struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowDefinitionId string                 `protobuf:"bytes,2,opt,name=workflow_definition_id,json=workflowDefinitionId,proto3" json:"workflow_definition_id,omitempty"`
	Status               InstanceStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=awm.v1.InstanceStatus" json:"status,omitempty"`
	Endpoints            *InstanceEndpoints     `protobuf:"bytes,4,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	HealthCheckAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=health_check_at,json=healthCheckAt,proto3" json:"health_check_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OrchestratorInstance) Reset() {
	*x = OrchestratorInstance{}
	mi := &file_awm_v1_public_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorInstance) ProtoMessage() {}

func (x *OrchestratorInstance) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorInstance.ProtoReflect.Descriptor instead.
func (*OrchestratorInstance) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{8}
}

func (x *OrchestratorInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrchestratorInstance) GetWorkflowDefinitionId() string {
	if x != nil {
		return x.WorkflowDefinitionId
	}
	return ""
}

func (x *OrchestratorInstance) GetStatus() InstanceStatus {
	if x != nil {
		return x.Status
	}
	return InstanceStatus_INSTANCE_STATUS_UNSPECIFIED
}

func (x *OrchestratorInstance) GetEndpoints() *InstanceEndpoints {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *OrchestratorInstance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrchestratorInstance) GetHealthCheckAt() *timestamppb.Timestamp {
	if x != nil {
		return x.HealthCheckAt
	}
	return nil
}

// InstanceEndpoints describes how agents and tools reach this instance.
type InstanceEndpoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          string                 `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`     // host:port for the Orchestrator gRPC service
	Rest          string                 `protobuf:"bytes,2,opt,name=rest,proto3" json:"rest,omitempty"`     // optional HTTP/REST gateway
	Health        string                 `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"` // HTTP health check URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceEndpoints) Reset() {
	*x = InstanceEndpoints{}
	mi := &file_awm_v1_public_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceEndpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceEndpoints) ProtoMessage() {}

func (x *InstanceEndpoints) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceEndpoints.ProtoReflect.Descriptor instead.
func (*InstanceEndpoints) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{9}
}

func (x *InstanceEndpoints) GetGrpc() string {
	if x != nil {
		return x.Grpc
	}
	return ""
}

func (x *InstanceEndpoints) GetRest() string {
	if x != nil {
		return x.Rest
	}
	return ""
}

func (x *InstanceEndpoints) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

type DeployWorkflowRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorkflowDefinitionId string                 `protobuf:"bytes,1,opt,name=workflow_definition_id,json=workflowDefinitionId,proto3" json:"workflow_definition_id,omitempty"`
	ResourceOverrides    map[string]string      `protobuf:"bytes,2,rep,name=resource_overrides,json=resourceOverrides,proto3" json:"resource_overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g. {"port": "50052"}
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeployWorkflowRequest) Reset() {
	*x = DeployWorkflowRequest{}
	mi := &file_awm_v1_public_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployWorkflowRequest) ProtoMessage() {}

func (x *DeployWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployWorkflowRequest.ProtoReflect.Descriptor instead.
func (*DeployWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{10}
}

func (x *DeployWorkflowRequest) GetWorkflowDefinitionId() string {
	if x != nil {
		return x.WorkflowDefinitionId
	}
	return ""
}

func (x *DeployWorkflowRequest) GetResourceOverrides() map[string]string {
	if x != nil {
		return x.ResourceOverrides
	}
	return nil
}

type DeployWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Instance      *OrchestratorInstance  `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployWorkflowResponse) Reset() {
	*x = DeployWorkflowResponse{}
	mi := &file_awm_v1_public_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployWorkflowResponse) ProtoMessage() {}

func (x *DeployWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployWorkflowResponse.ProtoReflect.Descriptor instead.
func (*DeployWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{11}
}

func (x *DeployWorkflowResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeployWorkflowResponse) GetInstance() *OrchestratorInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type GetInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceRequest) Reset() {
	*x = GetInstanceRequest{}
	mi := &file_awm_v1_public_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceRequest) ProtoMessage() {}

func (x *GetInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{12}
}

func (x *GetInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListInstancesRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorkflowDefinitionId string                 `protobuf:"bytes,1,opt,name=workflow_definition_id,json=workflowDefinitionId,proto3" json:"workflow_definition_id,omitempty"`
	StatusFilter         InstanceStatus         `protobuf:"varint,2,opt,name=status_filter,json=statusFilter,proto3,enum=awm.v1.InstanceStatus" json:"status_filter,omitempty"`
	PageSize             int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListInstancesRequest) Reset() {
	*x = ListInstancesRequest{}
	mi := &file_awm_v1_public_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesRequest) ProtoMessage() {}

func (x *ListInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListInstancesRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{13}
}

func (x *ListInstancesRequest) GetWorkflowDefinitionId() string {
	if x != nil {
		return x.WorkflowDefinitionId
	}
	return ""
}

func (x *ListInstancesRequest) GetStatusFilter() InstanceStatus {
	if x != nil {
		return x.StatusFilter
	}
	return InstanceStatus_INSTANCE_STATUS_UNSPECIFIED
}

func (x *ListInstancesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInstancesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListInstancesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Instances     []*OrchestratorInstance `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	NextPageToken string                  `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesResponse) Reset() {
	*x = ListInstancesResponse{}
	mi := &file_awm_v1_public_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesResponse) ProtoMessage() {}

func (x *ListInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListInstancesResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{14}
}

func (x *ListInstancesResponse) GetInstances() []*OrchestratorInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *ListInstancesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type StopInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Archive       bool                   `protobuf:"varint,2,opt,name=archive,proto3" json:"archive,omitempty"` // if true, preserve event log and task history
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInstanceRequest) Reset() {
	*x = StopInstanceRequest{}
	mi := &file_awm_v1_public_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInstanceRequest) ProtoMessage() {}

func (x *StopInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInstanceRequest.ProtoReflect.Descriptor instead.
func (*StopInstanceRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{15}
}

func (x *StopInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StopInstanceRequest) GetArchive() bool {
	if x != nil {
		return x.Archive
	}
	return false
}

type StopInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInstanceResponse) Reset() {
	*x = StopInstanceResponse{}
	mi := &file_awm_v1_public_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInstanceResponse) ProtoMessage() {}

func (x *StopInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInstanceResponse.ProtoReflect.Descriptor instead.
func (*StopInstanceResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{16}
}

func (x *StopInstanceResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

type StartWorkflowRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorkflowDefinitionId string                 `protobuf:"bytes,1,opt,name=workflow_definition_id,json=workflowDefinitionId,proto3" json:"workflow_definition_id,omitempty"`
	Tenant               string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Input                *structpb.Struct       `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`                                         // initial context passed to the first state
	IdempotencyKey       string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // prevents duplicate starts on retry
	ScheduledAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`          // if set, start at this time instead of now
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartWorkflowRequest) Reset() {
	*x = StartWorkflowRequest{}
	mi := &file_awm_v1_public_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowRequest) ProtoMessage() {}

func (x *StartWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StartWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{17}
}

func (x *StartWorkflowRequest) GetWorkflowDefinitionId() string {
	if x != nil {
		return x.WorkflowDefinitionId
	}
	return ""
}

func (x *StartWorkflowRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *StartWorkflowRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *StartWorkflowRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *StartWorkflowRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

type StartWorkflowResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorkflowInstanceId   string                 `protobuf:"bytes,1,opt,name=workflow_instance_id,json=workflowInstanceId,proto3" json:"workflow_instance_id,omitempty"`
	OrchestratorEndpoint string                 `protobuf:"bytes,2,opt,name=orchestrator_endpoint,json=orchestratorEndpoint,proto3" json:"orchestrator_endpoint,omitempty"` // gRPC address agents should connect to
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartWorkflowResponse) Reset() {
	*x = StartWorkflowResponse{}
	mi := &file_awm_v1_public_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowResponse) ProtoMessage() {}

func (x *StartWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowResponse.ProtoReflect.Descriptor instead.
func (*StartWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{18}
}

func (x *StartWorkflowResponse) GetWorkflowInstanceId() string {
	if x != nil {
		return x.WorkflowInstanceId
	}
	return ""
}

func (x *StartWorkflowResponse) GetOrchestratorEndpoint() string {
	if x != nil {
		return x.OrchestratorEndpoint
	}
	return ""
}

type SignalWorkflowRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkflowInstanceId string                 `protobuf:"bytes,1,opt,name=workflow_instance_id,json=workflowInstanceId,proto3" json:"workflow_instance_id,omitempty"`
	SignalName         string                 `protobuf:"bytes,2,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"` // e.g. "approval-granted", "timer-expired"
	Payload            *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignalWorkflowRequest) Reset() {
	*x = SignalWorkflowRequest{}
	mi := &file_awm_v1_public_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalWorkflowRequest) ProtoMessage() {}

func (x *SignalWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalWorkflowRequest.ProtoReflect.Descriptor instead.
func (*SignalWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{19}
}

func (x *SignalWorkflowRequest) GetWorkflowInstanceId() string {
	if x != nil {
		return x.WorkflowInstanceId
	}
	return ""
}

func (x *SignalWorkflowRequest) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *SignalWorkflowRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SignalWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalWorkflowResponse) Reset() {
	*x = SignalWorkflowResponse{}
	mi := &file_awm_v1_public_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalWorkflowResponse) ProtoMessage() {}

func (x *SignalWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalWorkflowResponse.ProtoReflect.Descriptor instead.
func (*SignalWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{20}
}

func (x *SignalWorkflowResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type CancelWorkflowRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkflowInstanceId string                 `protobuf:"bytes,1,opt,name=workflow_instance_id,json=workflowInstanceId,proto3" json:"workflow_instance_id,omitempty"`
	Reason             string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CancelWorkflowRequest) Reset() {
	*x = CancelWorkflowRequest{}
	mi := &file_awm_v1_public_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowRequest) ProtoMessage() {}

func (x *CancelWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CancelWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{21}
}

func (x *CancelWorkflowRequest) GetWorkflowInstanceId() string {
	if x != nil {
		return x.WorkflowInstanceId
	}
	return ""
}

func (x *CancelWorkflowRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowResponse) Reset() {
	*x = CancelWorkflowResponse{}
	mi := &file_awm_v1_public_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowResponse) ProtoMessage() {}

func (x *CancelWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awm_v1_public_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CancelWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_awm_v1_public_proto_rawDescGZIP(), []int{22}
}

func (x *CancelWorkflowResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_awm_v1_public_proto protoreflect.FileDescriptor

const file_awm_v1_public_proto_rawDesc = "" +
	"\n" +
	"\x13awm/v1/public.proto\x12\x06awm.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x02\n" +
	"\x12WorkflowDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rdefinition_id\x18\x04 \x01(\tR\fdefinitionId\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x12!\n" +
	"\fyaml_content\x18\x06 \x01(\tR\vyamlContent\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8f\x01\n" +
	"\x1fCreateWorkflowDefinitionRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fyaml_content\x18\x03 \x01(\tR\vyamlContent\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\".\n" +
	"\x1cGetWorkflowDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x1fUpdateWorkflowDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fyaml_content\x18\x02 \x01(\tR\vyamlContent\"1\n" +
	"\x1fDeleteWorkflowDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	" DeleteWorkflowDefinitionResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\x95\x01\n" +
	"\x1eListWorkflowDefinitionsRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1f\n" +
	"\vname_filter\x18\x02 \x01(\tR\n" +
	"nameFilter\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x87\x01\n" +
	"\x1fListWorkflowDefinitionsResponse\x12<\n" +
	"\vdefinitions\x18\x01 \x03(\v2\x1a.awm.v1.WorkflowDefinitionR\vdefinitions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xc4\x02\n" +
	"\x14OrchestratorInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x16workflow_definition_id\x18\x02 \x01(\tR\x14workflowDefinitionId\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.awm.v1.InstanceStatusR\x06status\x127\n" +
	"\tendpoints\x18\x04 \x01(\v2\x19.awm.v1.InstanceEndpointsR\tendpoints\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12B\n" +
	"\x0fhealth_check_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rhealthCheckAt\"S\n" +
	"\x11InstanceEndpoints\x12\x12\n" +
	"\x04grpc\x18\x01 \x01(\tR\x04grpc\x12\x12\n" +
	"\x04rest\x18\x02 \x01(\tR\x04rest\x12\x16\n" +
	"\x06health\x18\x03 \x01(\tR\x06health\"\xf8\x01\n" +
	"\x15DeployWorkflowRequest\x124\n" +
	"\x16workflow_definition_id\x18\x01 \x01(\tR\x14workflowDefinitionId\x12c\n" +
	"\x12resource_overrides\x18\x02 \x03(\v24.awm.v1.DeployWorkflowRequest.ResourceOverridesEntryR\x11resourceOverrides\x1aD\n" +
	"\x16ResourceOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\x16DeployWorkflowResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x128\n" +
	"\binstance\x18\x02 \x01(\v2\x1c.awm.v1.OrchestratorInstanceR\binstance\"$\n" +
	"\x12GetInstanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc5\x01\n" +
	"\x14ListInstancesRequest\x124\n" +
	"\x16workflow_definition_id\x18\x01 \x01(\tR\x14workflowDefinitionId\x12;\n" +
	"\rstatus_filter\x18\x02 \x01(\x0e2\x16.awm.v1.InstanceStatusR\fstatusFilter\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"{\n" +
	"\x15ListInstancesResponse\x12:\n" +
	"\tinstances\x18\x01 \x03(\v2\x1c.awm.v1.OrchestratorInstanceR\tinstances\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"?\n" +
	"\x13StopInstanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aarchive\x18\x02 \x01(\bR\aarchive\"0\n" +
	"\x14StopInstanceResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\"\xfb\x01\n" +
	"\x14StartWorkflowRequest\x124\n" +
	"\x16workflow_definition_id\x18\x01 \x01(\tR\x14workflowDefinitionId\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12-\n" +
	"\x05input\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05input\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12=\n" +
	"\fscheduled_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\"~\n" +
	"\x15StartWorkflowResponse\x120\n" +
	"\x14workflow_instance_id\x18\x01 \x01(\tR\x12workflowInstanceId\x123\n" +
	"\x15orchestrator_endpoint\x18\x02 \x01(\tR\x14orchestratorEndpoint\"\x9d\x01\n" +
	"\x15SignalWorkflowRequest\x120\n" +
	"\x14workflow_instance_id\x18\x01 \x01(\tR\x12workflowInstanceId\x12\x1f\n" +
	"\vsignal_name\x18\x02 \x01(\tR\n" +
	"signalName\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\"4\n" +
	"\x16SignalWorkflowResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"a\n" +
	"\x15CancelWorkflowRequest\x120\n" +
	"\x14workflow_instance_id\x18\x01 \x01(\tR\x12workflowInstanceId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"4\n" +
	"\x16CancelWorkflowResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted*\xc8\x01\n" +
	"\x0eInstanceStatus\x12\x1f\n" +
	"\x1bINSTANCE_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cINSTANCE_STATUS_PROVISIONING\x10\x01\x12\x1a\n" +
	"\x16INSTANCE_STATUS_ACTIVE\x10\x02\x12\x1c\n" +
	"\x18INSTANCE_STATUS_DEGRADED\x10\x03\x12\x1b\n" +
	"\x17INSTANCE_STATUS_STOPPED\x10\x04\x12\x1c\n" +
	"\x18INSTANCE_STATUS_ARCHIVED\x10\x052\xa3\b\n" +
	"\x06Public\x12_\n" +
	"\x18CreateWorkflowDefinition\x12'.awm.v1.CreateWorkflowDefinitionRequest\x1a\x1a.awm.v1.WorkflowDefinition\x12Y\n" +
	"\x15GetWorkflowDefinition\x12$.awm.v1.GetWorkflowDefinitionRequest\x1a\x1a.awm.v1.WorkflowDefinition\x12_\n" +
	"\x18UpdateWorkflowDefinition\x12'.awm.v1.UpdateWorkflowDefinitionRequest\x1a\x1a.awm.v1.WorkflowDefinition\x12m\n" +
	"\x18DeleteWorkflowDefinition\x12'.awm.v1.DeleteWorkflowDefinitionRequest\x1a(.awm.v1.DeleteWorkflowDefinitionResponse\x12j\n" +
	"\x17ListWorkflowDefinitions\x12&.awm.v1.ListWorkflowDefinitionsRequest\x1a'.awm.v1.ListWorkflowDefinitionsResponse\x12O\n" +
	"\x0eDeployWorkflow\x12\x1d.awm.v1.DeployWorkflowRequest\x1a\x1e.awm.v1.DeployWorkflowResponse\x12G\n" +
	"\vGetInstance\x12\x1a.awm.v1.GetInstanceRequest\x1a\x1c.awm.v1.OrchestratorInstance\x12L\n" +
	"\rListInstances\x12\x1c.awm.v1.ListInstancesRequest\x1a\x1d.awm.v1.ListInstancesResponse\x12I\n" +
	"\fStopInstance\x12\x1b.awm.v1.StopInstanceRequest\x1a\x1c.awm.v1.StopInstanceResponse\x12L\n" +
	"\rStartWorkflow\x12\x1c.awm.v1.StartWorkflowRequest\x1a\x1d.awm.v1.StartWorkflowResponse\x12O\n" +
	"\x0eSignalWorkflow\x12\x1d.awm.v1.SignalWorkflowRequest\x1a\x1e.awm.v1.SignalWorkflowResponse\x12O\n" +
	"\x0eCancelWorkflow\x12\x1d.awm.v1.CancelWorkflowRequest\x1a\x1e.awm.v1.CancelWorkflowResponseB5Z3github.com/autocondat/awm-proto/gen/go/awm/v1;awmv1b\x06proto3"

var (
	file_awm_v1_public_proto_rawDescOnce sync.Once
	file_awm_v1_public_proto_rawDescData []byte
)

func file_awm_v1_public_proto_rawDescGZIP() []byte {
	file_awm_v1_public_proto_rawDescOnce.Do(func() {
		file_awm_v1_public_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_awm_v1_public_proto_rawDesc), len(file_awm_v1_public_proto_rawDesc)))
	})
	return file_awm_v1_public_proto_rawDescData
}

var file_awm_v1_public_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_awm_v1_public_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_awm_v1_public_proto_goTypes = []any{
	(InstanceStatus)(0),                      // 0: awm.v1.InstanceStatus
	(*WorkflowDefinition)(nil),               // 1: awm.v1.WorkflowDefinition
	(*CreateWorkflowDefinitionRequest)(nil),  // 2: awm.v1.CreateWorkflowDefinitionRequest
	(*GetWorkflowDefinitionRequest)(nil),     // 3: awm.v1.GetWorkflowDefinitionRequest
	(*UpdateWorkflowDefinitionRequest)(nil),  // 4: awm.v1.UpdateWorkflowDefinitionRequest
	(*DeleteWorkflowDefinitionRequest)(nil),  // 5: awm.v1.DeleteWorkflowDefinitionRequest
	(*DeleteWorkflowDefinitionResponse)(nil), // 6: awm.v1.DeleteWorkflowDefinitionResponse
	(*ListWorkflowDefinitionsRequest)(nil),   // 7: awm.v1.ListWorkflowDefinitionsRequest
	(*ListWorkflowDefinitionsResponse)(nil),  // 8: awm.v1.ListWorkflowDefinitionsResponse
	(*OrchestratorInstance)(nil),             // 9: awm.v1.OrchestratorInstance
	(*InstanceEndpoints)(nil),                // 10: awm.v1.InstanceEndpoints
	(*DeployWorkflowRequest)(nil),            // 11: awm.v1.DeployWorkflowRequest
	(*DeployWorkflowResponse)(nil),           // 12: awm.v1.DeployWorkflowResponse
	(*GetInstanceRequest)(nil),               // 13: awm.v1.GetInstanceRequest
	(*ListInstancesRequest)(nil),             // 14: awm.v1.ListInstancesRequest
	(*ListInstancesResponse)(nil),            // 15: awm.v1.ListInstancesResponse
	(*StopInstanceRequest)(nil),              // 16: awm.v1.StopInstanceRequest
	(*StopInstanceResponse)(nil),             // 17: awm.v1.StopInstanceResponse
	(*StartWorkflowRequest)(nil),             // 18: awm.v1.StartWorkflowRequest
	(*StartWorkflowResponse)(nil),            // 19: awm.v1.StartWorkflowResponse
	(*SignalWorkflowRequest)(nil),            // 20: awm.v1.SignalWorkflowRequest
	(*SignalWorkflowResponse)(nil),           // 21: awm.v1.SignalWorkflowResponse
	(*CancelWorkflowRequest)(nil),            // 22: awm.v1.CancelWorkflowRequest
	(*CancelWorkflowResponse)(nil),           // 23: awm.v1.CancelWorkflowResponse
	nil,                                      // 24: awm.v1.DeployWorkflowRequest.ResourceOverridesEntry
	(*timestamppb.Timestamp)(nil),            // 25: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                  // 26: google.protobuf.Struct
}
var file_awm_v1_public_proto_depIdxs = []int32{
	25, // 0: awm.v1.WorkflowDefinition.created_at:type_name -> google.protobuf.Timestamp
	25, // 1: awm.v1.WorkflowDefinition.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: awm.v1.ListWorkflowDefinitionsResponse.definitions:type_name -> awm.v1.WorkflowDefinition
	0,  // 3: awm.v1.OrchestratorInstance.status:type_name -> awm.v1.InstanceStatus
	10, // 4: awm.v1.OrchestratorInstance.endpoints:type_name -> awm.v1.InstanceEndpoints
	25, // 5: awm.v1.OrchestratorInstance.created_at:type_name -> google.protobuf.Timestamp
	25, // 6: awm.v1.OrchestratorInstance.health_check_at:type_name -> google.protobuf.Timestamp
	24, // 7: awm.v1.DeployWorkflowRequest.resource_overrides:type_name -> awm.v1.DeployWorkflowRequest.ResourceOverridesEntry
	9,  // 8: awm.v1.DeployWorkflowResponse.instance:type_name -> awm.v1.OrchestratorInstance
	0,  // 9: awm.v1.ListInstancesRequest.status_filter:type_name -> awm.v1.InstanceStatus
	9,  // 10: awm.v1.ListInstancesResponse.instances:type_name -> awm.v1.OrchestratorInstance
	26, // 11: awm.v1.StartWorkflowRequest.input:type_name -> google.protobuf.Struct
	25, // 12: awm.v1.StartWorkflowRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	26, // 13: awm.v1.SignalWorkflowRequest.payload:type_name -> google.protobuf.Struct
	2,  // 14: awm.v1.Public.CreateWorkflowDefinition:input_type -> awm.v1.CreateWorkflowDefinitionRequest
	3,  // 15: awm.v1.Public.GetWorkflowDefinition:input_type -> awm.v1.GetWorkflowDefinitionRequest
	4,  // 16: awm.v1.Public.UpdateWorkflowDefinition:input_type -> awm.v1.UpdateWorkflowDefinitionRequest
	5,  // 17: awm.v1.Public.DeleteWorkflowDefinition:input_type -> awm.v1.DeleteWorkflowDefinitionRequest
	7,  // 18: awm.v1.Public.ListWorkflowDefinitions:input_type -> awm.v1.ListWorkflowDefinitionsRequest
	11, // 19: awm.v1.Public.DeployWorkflow:input_type -> awm.v1.DeployWorkflowRequest
	13, // 20: awm.v1.Public.GetInstance:input_type -> awm.v1.GetInstanceRequest
	14, // 21: awm.v1.Public.ListInstances:input_type -> awm.v1.ListInstancesRequest
	16, // 22: awm.v1.Public.StopInstance:input_type -> awm.v1.StopInstanceRequest
	18, // 23: awm.v1.Public.StartWorkflow:input_type -> awm.v1.StartWorkflowRequest
	20, // 24: awm.v1.Public.SignalWorkflow:input_type -> awm.v1.SignalWorkflowRequest
	22, // 25: awm.v1.Public.CancelWorkflow:input_type -> awm.v1.CancelWorkflowRequest
	1,  // 26: awm.v1.Public.CreateWorkflowDefinition:output_type -> awm.v1.WorkflowDefinition
	1,  // 27: awm.v1.Public.GetWorkflowDefinition:output_type -> awm.v1.WorkflowDefinition
	1,  // 28: awm.v1.Public.UpdateWorkflowDefinition:output_type -> awm.v1.WorkflowDefinition
	6,  // 29: awm.v1.Public.DeleteWorkflowDefinition:output_type -> awm.v1.DeleteWorkflowDefinitionResponse
	8,  // 30: awm.v1.Public.ListWorkflowDefinitions:output_type -> awm.v1.ListWorkflowDefinitionsResponse
	12, // 31: awm.v1.Public.DeployWorkflow:output_type -> awm.v1.DeployWorkflowResponse
	9,  // 32: awm.v1.Public.GetInstance:output_type -> awm.v1.OrchestratorInstance
	15, // 33: awm.v1.Public.ListInstances:output_type -> awm.v1.ListInstancesResponse
	17, // 34: awm.v1.Public.StopInstance:output_type -> awm.v1.StopInstanceResponse
	19, // 35: awm.v1.Public.StartWorkflow:output_type -> awm.v1.StartWorkflowResponse
	21, // 36: awm.v1.Public.SignalWorkflow:output_type -> awm.v1.SignalWorkflowResponse
	23, // 37: awm.v1.Public.CancelWorkflow:output_type -> awm.v1.CancelWorkflowResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_awm_v1_public_proto_init() }
func file_awm_v1_public_proto_init() {
	if File_awm_v1_public_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_awm_v1_public_proto_rawDesc), len(file_awm_v1_public_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_awm_v1_public_proto_goTypes,
		DependencyIndexes: file_awm_v1_public_proto_depIdxs,
		EnumInfos:         file_awm_v1_public_proto_enumTypes,
		MessageInfos:      file_awm_v1_public_proto_msgTypes,
	}.Build()
	File_awm_v1_public_proto = out.File
	file_awm_v1_public_proto_goTypes = nil
	file_awm_v1_public_proto_depIdxs = nil
}
